### ISSUE TITLE
vmod_tcp: format error in log when built on 32bit, as VCL_INT does not match %lu

### ISSUE THREAD

**Issue by ingvarha** [varnish/varnish-modules#118] opened 2018-08-07 13:53 UTC
When building varnish-modules-0.15 for el6/i686, VCL_INT is not "long unsigned int", so using %lu for formatting does not work, and gcc goes

vmod_tcp.c:177: error: format '%lu' expects type 'long unsigned int', but argument 4 has type 'VCL_INT'

Line 177 looks like this:

VSLb(ctx->vsl, SLT_VCL_Log, "vmod-tcp: Socket paced to %lu KB/s.", rate);

Ingvar

**Comment by Dridi** [comment] 2018-08-07 14:32
Duplicate of #117.

**Closed by Dridi** 2018-08-07 14:32 UTC
