### ISSUE TITLE
Compile error with Varnish 6.1

### ISSUE THREAD

**Issue by razvanphp** [varnish/varnish-modules#128] opened 2018-11-21 10:43 UTC
Sorry for the format, we use packer for builds...

```
 (item=/usr/bin/make) => {"changed": true, "cmd": ["/usr/bin/make"], "delta": "0:00:01.520934", "end": "2018-11-21 10:36:16.664124", "item": "/usr/bin/make", "msg": "non-zero return code", "rc": 2, "start": "2018-11-21 10:36:15.143190", "stderr": "vmod_saintmode.c: In function ‘healthy’:\nvmod_saintmode.c:272:17: error: ‘const struct director’ has no member named ‘healthy’\n   return (sm->be->healthy(sm->be, bo, changed));\n                 ^~\nvmod_saintmode.c:285:25: error: ‘const struct director’ has no member named ‘healthy’\n  return (retval ? sm->be->healthy(sm->be, bo, changed) : 0);\n                         ^~\nvmod_saintmode.c: In function ‘vmod_saintmode__init’:\nvmod_saintmode.c:346:10: error: ‘struct director’ has no member named ‘resolve’\n  sm->sdir->resolve = resolve;\n          ^~\nvmod_saintmode.c:347:10: error: ‘struct director’ has no member named ‘healthy’\n  sm->sdir->healthy = healthy;\n          ^~\nvmod_saintmode.c:352:10: error: ‘struct director’ has no member named ‘name’\n  sm->sdir->name = \"saintmode\";\n          ^~\nvmod_saintmode.c: In function ‘healthy’:\nvmod_saintmode.c:286:1: error: control reaches end of non-void function [-Werror=return-type]\n }\n ^\ncc1: all warnings being treated as errors\nmake[2]: *** [vmod_saintmode.lo] Error 1\nmake[1]: *** [all-recursive] Error 1\nmake: *** [all] Error 2", "stderr_lines": ["vmod_saintmode.c: In function ‘healthy’:", "vmod_saintmode.c:272:17: error: ‘const struct director’ has no member named ‘healthy’", "   return (sm->be->healthy(sm->be, bo, changed));", "                 ^~", "vmod_saintmode.c:285:25: error: ‘const struct director’ has no member named ‘healthy’", "  return (retval ? sm->be->healthy(sm->be, bo, changed) : 0);", "                         ^~", "vmod_saintmode.c: In function ‘vmod_saintmode__init’:", "vmod_saintmode.c:346:10: error: ‘struct director’ has no member named ‘resolve’", "  sm->sdir->resolve = resolve;", "          ^~", "vmod_saintmode.c:347:10: error: ‘struct director’ has no member named ‘healthy’", "  sm->sdir->healthy = healthy;", "          ^~", "vmod_saintmode.c:352:10: error: ‘struct director’ has no member named ‘name’", "  sm->sdir->name = \"saintmode\";", "          ^~", "vmod_saintmode.c: In function ‘healthy’:", "vmod_saintmode.c:286:1: error: control reaches end of non-void function [-Werror=return-type]", " }", " ^", "cc1: all warnings being treated as errors", "make[2]: *** [vmod_saintmode.lo] Error 1", "make[1]: *** [all-recursive] Error 1", "make: *** [all] Error 2"], "stdout": "/usr/bin/make  all-recursive\nmake[1]: Entering directory '/tmp/varnish-modules-0.15.0'\nMaking all in src\nmake[2]: Entering directory '/tmp/varnish-modules-0.15.0/src'\n  VMODTOOL vcc_bodyaccess_if.c\n  CC       vmod_bodyaccess.lo\n  CC       vcc_bodyaccess_if.lo\n  CCLD     libvmod_bodyaccess.la\n  VMODTOOL vcc_cookie_if.c\n  CC       vmod_cookie.lo\n  CC       vcc_cookie_if.lo\n  CCLD     libvmod_cookie.la\n  VMODTOOL vcc_header_if.c\n  CC       vmod_header.lo\n  CC       vcc_header_if.lo\n  CCLD     libvmod_header.la\n  VMODTOOL vcc_saintmode_if.c\n  CC       vmod_saintmode.lo\nMakefile:915: recipe for target 'vmod_saintmode.lo' failed\nmake[2]: Leaving directory '/tmp/varnish-modules-0.15.0/src'\nMakefile:537: recipe for target 'all-recursive' failed\nmake[1]: Leaving directory '/tmp/varnish-modules-0.15.0'\nMakefile:448: recipe for target 'all' failed", "stdout_lines": ["/usr/bin/make  all-recursive", "make[1]: Entering directory '/tmp/varnish-modules-0.15.0'", "Making all in src", "make[2]: Entering directory '/tmp/varnish-modules-0.15.0/src'", "  VMODTOOL vcc_bodyaccess_if.c", "  CC       vmod_bodyaccess.lo", "  CC       vcc_bodyaccess_if.lo", "  CCLD     libvmod_bodyaccess.la", "  VMODTOOL vcc_cookie_if.c", "  CC       vmod_cookie.lo", "  CC       vcc_cookie_if.lo", "  CCLD     libvmod_cookie.la", "  VMODTOOL vcc_header_if.c", "  CC       vmod_header.lo", "  CC       vcc_header_if.lo", "  CCLD     libvmod_header.la", "  VMODTOOL vcc_saintmode_if.c", "  CC       vmod_saintmode.lo", "Makefile:915: recipe for target 'vmod_saintmode.lo' failed", "make[2]: Leaving directory '/tmp/varnish-modules-0.15.0/src'", "Makefile:537: recipe for target 'all-recursive' failed", "make[1]: Leaving directory '/tmp/varnish-modules-0.15.0'", "Makefile:448: recipe for target 'all' failed"]}
```

Any idea?

**Comment by Dridi** [comment] 2018-11-21 11:37
Dupe of #119 among others.

**Closed by Dridi** 2018-11-21 11:37 UTC
